

version: '3.8'
services: 
  dev-database:
    image: postgres:15.0
    ports:
      - 5434:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Abc123456
      POSTGRES_DB: burogu-db
    networks:
      - nestjs-network
networks:
  nestjs-network:
