export enum HttpStatus {
    ERROR = 400,
    SUCCESS = 200,
    CREATED = 201,
    UNAUTHORIZED = 401,
    FORBIDDEN = 403,
    NOT_FOUND = 404,
    CONFLICT = 409,
    BAD_REQUEST = 400,
    PAYMENT_REQUIRED = 402,
    METHOD_NOT_ALLOWED = 405,
    REQUEST_TIMEOUT = 408,
    INTERNAL_SERVER_ERROR = 500,
    NOT_IMPLEMENTED = 501,
    BAD_GATEWAY = 502,
    SERVICE_UNAVAILABLE = 503,
    GATEWAY_TIMEOUT = 504,
}

export enum HttpMessage {
    ERROR_INTERNAL_SERVER = 'Internal Server Error',
    ERROR_UNAUTHORIZED = 'Unauthorized',
    ERROR_FORBIDDEN = 'Forbidden',
    ERROR_NOT_FOUND = 'Not Found',
    ERROR_CONFLICT = 'Conflict',
    ERROR_BAD_REQUEST = 'Bad Request',
    ERROR_PAYMENT_REQUIRED = 'Payment Required',
    ERROR_METHOD_NOT_ALLOWED = 'Method Not Allowed',
    ERROR_REQUEST_TIMEOUT = 'Request Timeout',
    ERROR_BAD_GATEWAY = 'Bad Gateway',
    ERROR_SERVICE_UNAVAILABLE = 'Service Unavailable',
    ERROR_GATEWAY_TIMEOUT = 'Gateway Timeout',
    
    SUCCESS_OK = 'OK',
    SUCCESS_CREATED = 'Created',
    SUCCESS_UPDATED = 'Updated',
    SUCCESS_DELETED = 'Deleted',
    SUCCESS_LISTED = 'Listed',
    SUCCESS_NO_CONTENT = 'No Content',
    SUCCESS_PARTIAL_CONTENT = 'Partial Content',
    SUCCESS_ACCEPTED = 'Accepted',
}
